apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-cicd-test001
  labels:
    app: node-cicd-test001
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-cicd-test001
  template:
    metadata:
      labels:
        app: node-cicd-test001
    spec:
      containers:
        - name: node-cicd-test001
          image: buerl/node-cicd-test001:latest
          imagePullPolicy: Always # 作用：Always 强制从镜像仓库拉取镜像
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
            # livenessProbe:
            #   httpGet:
            #     path: /
            #     port: 3000
            #   initialDelaySeconds: 10
            #   periodSeconds: 10